parameters:
- name: endpoint
  type: string

steps:
- task: GitHubRelease@0
  inputs:
    gitHubConnection: ${{ parameters.endpoint }}
    repositoryName: ubolonton/emacs-tree-sitter
    isDraft: true
    assetUploadMode: replace
    assets: |
      $(System.DefaultWorkingDirectory)/dist/*.tar.gz
      $(System.DefaultWorkingDirectory)/core/lts-dyn.*
