name: Integ

on:
  workflow_dispatch:
    inputs:
      revision:
        required: true
        default: 'master'

jobs:
  integ:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.15
          - ubuntu-18.04
          - windows-2019
        emacs-version:
          - '27.2'
          - '28.1'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: purcell/setup-emacs@b56a75706e31e22d474357c77fb25ce73be2973a
        if: runner.os != 'Windows'
        with:
          version: ${{ matrix.emacs-version }}

      - uses: jcs090218/setup-emacs-windows@6e1ba035e1387639a42f4ef4872598c88481c863
        if: runner.os == 'Windows'
        with:
          version: ${{ matrix.emacs-version }}

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.revision }}

      - run: .github/script/setup-cask
      - run: bin/setup

      - run: bin/test integ
